import type { FeaturePageConfig } from "@/components/ui/FeaturePageView";
import {
  type AnalyticsResponse,
  type HistoryResponse,
  type OpportunitiesResponse,
  type PortfolioSummaryResponse,
  type SettingsResponse,
  type StrategiesResponse,
  type WatchlistResponse,
  formatFeatureBoolean,
  formatFeatureCurrency,
  formatFeaturePercent,
} from "@/lib/backend-data";
import { featurePageConfigs } from "@/lib/feature-pages";

type PageKey = keyof typeof featurePageConfigs;

function getBaseConfig(page: PageKey): FeaturePageConfig {
  return featurePageConfigs[page];
}

function getTone(index: number) {
  if (index === 0) return "green" as const;
  if (index === 1) return "teal" as const;
  return "white" as const;
}

export function mapPortfolioApiToFeatureConfig(
  data: PortfolioSummaryResponse,
): FeaturePageConfig {
  const base = getBaseConfig("portfolio");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Total Portfolio",
        value: formatFeatureCurrency(data.hero.totalPortfolio),
        helper: `${data.hero.trackedPositions} tracked positions`,
      },
      {
        label: "Idle Capital",
        value: formatFeatureCurrency(data.hero.idleCapital),
        helper: "Ready for optimization",
        tone: "green",
      },
      {
        label: "0G Network Sync",
        value: `${data.hero.syncPct.toFixed(1)}%`,
        helper: data.reviewerNotes.syncStatus,
        tone: "teal",
      },
      {
        label: "Tracked Positions",
        value: String(data.hero.trackedPositions),
        helper: data.health.riskProfile,
      },
    ],
    highlight: {
      ...base.highlight,
      rows: data.allocation.slice(0, 4).map((item, index) => ({
        label: item.symbol,
        value: `${item.pct.toFixed(1)}%`,
        helper: item.note,
        tone: getTone(index),
      })),
      footer: data.reviewerNotes.syncStatus,
    },
    table: {
      ...base.table,
      rows: data.positions.slice(0, 4).map((item) => ({
        cells: [
          item.asset,
          item.protocol,
          formatFeaturePercent(item.apy),
          item.exposure,
        ],
        badge: item.state,
      })),
      footnote: data.health.riskProfile,
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Diversification",
            value: data.health.diversification,
            tone: "green",
          },
          {
            label: "Slippage Budget",
            value: data.health.slippageBudget,
            tone: "white",
          },
          {
            label: "Risk Profile",
            value: data.health.riskProfile,
            tone: "teal",
          },
        ],
        footer: "Live summary generated from the portfolio backend route.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Sync Status",
            value: data.reviewerNotes.syncStatus,
            tone: "teal",
          },
          {
            label: "Next Trigger",
            value: data.reviewerNotes.nextTrigger,
            tone: "green",
          },
          {
            label: "Proof Mode",
            value: data.reviewerNotes.proofMode,
            tone: "white",
          },
        ],
        footer: "Fallback stays on the existing mock config if this API ever fails.",
      },
    ],
  };
}

export function mapStrategiesApiToFeatureConfig(
  data: StrategiesResponse,
): FeaturePageConfig {
  const base = getBaseConfig("strategies");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Live Strategies",
        value: String(data.hero.liveStrategies),
        helper: data.queue.queuedTemplates,
      },
      {
        label: "Avg Confidence",
        value: `${data.hero.avgConfidence}%`,
        helper: "Across current strategy templates",
        tone: "green",
      },
      {
        label: "Simulated Routes",
        value: String(data.hero.simulatedRoutes),
        helper: "Generated by the optimizer engine",
        tone: "teal",
      },
      {
        label: "Guardrails Active",
        value: String(data.hero.guardrailsActive),
        helper: data.guardrails.proofRequirement,
      },
    ],
    highlight: {
      ...base.highlight,
      rows: data.stack.slice(0, 4).map((item, index) => ({
        label: item.label,
        value: item.value,
        helper: item.note,
        tone: getTone(index),
      })),
      footer: "Mapped from /api/strategies with zero layout changes.",
    },
    table: {
      ...base.table,
      rows: data.templates.slice(0, 4).map((item) => ({
        cells: [item.name, item.target, item.risk, item.trigger],
        badge: item.state,
      })),
      footnote: data.queue.needsManualReview,
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Max Slippage",
            value: data.guardrails.maxSlippage,
            tone: "green",
          },
          {
            label: "Risk Escalation",
            value: data.guardrails.riskEscalation,
            tone: "white",
          },
          {
            label: "Proof Requirement",
            value: data.guardrails.proofRequirement,
            tone: "teal",
          },
        ],
        footer: "Guardrails are now sourced from the backend-ready response shape.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Queued Templates",
            value: data.queue.queuedTemplates,
            tone: "teal",
          },
          {
            label: "Auto-Eligible",
            value: data.queue.autoEligible,
            tone: "green",
          },
          {
            label: "Needs Manual Review",
            value: data.queue.needsManualReview,
            tone: "white",
          },
        ],
        footer: "The queue card now reflects live route data coming from the API layer.",
      },
    ],
  };
}

export function mapOpportunitiesApiToFeatureConfig(
  data: OpportunitiesResponse,
): FeaturePageConfig {
  const base = getBaseConfig("opportunities");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Top Estimated APY",
        value: formatFeaturePercent(data.hero.topEstimatedApy),
        helper: "Current best low-risk route",
        tone: "green",
      },
      {
        label: "Signals Monitored",
        value: String(data.hero.signalsMonitored),
        helper: "Liquidity, momentum, and slippage",
        tone: "teal",
      },
      {
        label: "Opportunities Ready",
        value: String(data.hero.opportunitiesReady),
        helper: data.executionReadiness.autoExecutable,
      },
      {
        label: "Proof-Eligible",
        value: `${data.hero.proofEligiblePct}%`,
        helper: data.selectionLogic.proofGate,
      },
    ],
    highlight: {
      ...base.highlight,
      rows: data.rankedHighlights.slice(0, 4).map((item, index) => ({
        label: item.label,
        value: item.value,
        helper: item.note,
        tone: getTone(index),
      })),
      footer: "Opportunity ranking is now backend-fed with mock-safe fallback.",
    },
    table: {
      ...base.table,
      rows: data.board.slice(0, 4).map((item) => ({
        cells: [item.route, item.apy, item.risk, item.liquidity],
        badge: item.state,
      })),
      footnote: data.executionReadiness.slippageWindow,
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Momentum Weight",
            value: data.selectionLogic.momentumWeight,
            tone: "teal",
          },
          {
            label: "Risk Filter",
            value: data.selectionLogic.riskFilter,
            tone: "white",
          },
          {
            label: "Proof Gate",
            value: data.selectionLogic.proofGate,
            tone: "green",
          },
        ],
        footer: "Selection logic now follows the API response instead of hardcoded page content.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Auto-Executable",
            value: data.executionReadiness.autoExecutable,
            tone: "green",
          },
          {
            label: "Manual Review",
            value: data.executionReadiness.manualReview,
            tone: "white",
          },
          {
            label: "Slippage Window",
            value: data.executionReadiness.slippageWindow,
            tone: "teal",
          },
        ],
        footer: "Execution readiness is now mapped from a backend domain object.",
      },
    ],
  };
}

export function mapHistoryApiToFeatureConfig(
  data: HistoryResponse,
): FeaturePageConfig {
  const base = getBaseConfig("history");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Optimization Runs",
        value: String(data.hero.runs),
        helper: `${data.hero.proofEntries} proof entries`,
      },
      {
        label: "Success Rate",
        value: `${data.hero.successRate}%`,
        helper: "Completed without breaking risk rules",
        tone: "green",
      },
      {
        label: "Proof Entries",
        value: String(data.hero.proofEntries),
        helper: data.verification.storageAnchor,
        tone: "teal",
      },
      {
        label: "Value Routed",
        value: formatFeatureCurrency(data.hero.valueRouted),
        helper: data.latestOutcome.executionTime,
      },
    ],
    highlight: {
      ...base.highlight,
      rows: data.timeline.slice(0, 4).map((item, index) => ({
        label: item.time,
        value: item.value,
        helper: item.note,
        tone: getTone(index),
      })),
      footer: data.verification.reviewStatus,
    },
    table: {
      ...base.table,
      rows: data.ledger.slice(0, 4).map((item) => ({
        cells: [item.timestamp, item.action, item.cid, item.explorer],
        badge: item.state,
      })),
      footnote: data.verification.explorerSource,
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Realized APY Lift",
            value: data.latestOutcome.realizedApyLift,
            tone: "green",
          },
          {
            label: "Annualized Gain",
            value: data.latestOutcome.annualizedGain,
            tone: "white",
          },
          {
            label: "Execution Time",
            value: data.latestOutcome.executionTime,
            tone: "teal",
          },
        ],
        footer: "Latest outcome now comes straight from the history API payload.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Explorer Source",
            value: data.verification.explorerSource,
            tone: "teal",
          },
          {
            label: "Storage Anchor",
            value: data.verification.storageAnchor,
            tone: "green",
          },
          {
            label: "Review Status",
            value: data.verification.reviewStatus,
            tone: "white",
          },
        ],
        footer: "The verification card now reflects the proof ledger endpoint.",
      },
    ],
  };
}

export function mapAnalyticsApiToFeatureConfig(
  data: AnalyticsResponse,
): FeaturePageConfig {
  const base = getBaseConfig("analytics");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Avg APY Lift",
        value: data.hero.avgApyLift,
        helper: data.overview[0]?.note ?? base.heroMetrics[0].helper,
        tone: "green",
      },
      {
        label: "Avg Execution",
        value: data.hero.avgExecution,
        helper: data.overview[1]?.note ?? base.heroMetrics[1].helper,
        tone: "teal",
      },
      {
        label: "Compute Jobs",
        value: data.hero.computeJobs,
        helper: data.efficiency.computeEfficiency,
      },
      {
        label: "Uptime",
        value: data.hero.uptime,
        helper: data.efficiency.explorerCoverage,
      },
    ],
    highlight: {
      ...base.highlight,
      rows: data.overview.slice(0, 4).map((item, index) => ({
        label: item.label,
        value: item.value,
        helper: item.note,
        tone: getTone(index),
      })),
      footer: "Overview cards are now hydrated from /api/analytics.",
    },
    table: {
      ...base.table,
      rows: data.matrix.slice(0, 4).map((item) => ({
        cells: [item.metric, item.current, item.benchmark, item.direction],
        badge: item.state,
      })),
      footnote: data.modelConfidence.userExplainability,
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Compute Efficiency",
            value: data.efficiency.computeEfficiency,
            tone: "green",
          },
          {
            label: "Storage Footprint",
            value: data.efficiency.storageFootprint,
            tone: "white",
          },
          {
            label: "Explorer Coverage",
            value: data.efficiency.explorerCoverage,
            tone: "teal",
          },
        ],
        footer: "Efficiency metrics now come from the analytics backend response.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Average Confidence",
            value: data.modelConfidence.averageConfidence,
            tone: "teal",
          },
          {
            label: "Fallback Usage",
            value: data.modelConfidence.fallbackUsage,
            tone: "green",
          },
          {
            label: "Explainability",
            value: data.modelConfidence.userExplainability,
            tone: "white",
          },
        ],
        footer: "Model confidence remains visible while using a consistent page shell.",
      },
    ],
  };
}

export function mapWatchlistApiToFeatureConfig(
  data: WatchlistResponse,
): FeaturePageConfig {
  const base = getBaseConfig("watchlist");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Watched Pools",
        value: String(data.hero.watchedPools),
        helper: data.quickActions.archiveSignal,
      },
      {
        label: "Hot Signals",
        value: String(data.hero.hotSignals),
        helper: data.conditions.yieldDelta,
        tone: "green",
      },
      {
        label: "Idle Candidates",
        value: String(data.hero.idleCandidates),
        helper: data.quickActions.promoteToOpportunity,
        tone: "teal",
      },
      {
        label: "Alerts Today",
        value: String(data.hero.alertsToday),
        helper: data.quickActions.sendToAgent,
      },
    ],
    highlight: {
      ...base.highlight,
      rows: data.protocolsUnderWatch.slice(0, 4).map((item, index) => ({
        label: item.label,
        value: item.value,
        helper: item.note,
        tone: getTone(index),
      })),
      footer: "Watch signals are now injected from the watchlist API route.",
    },
    table: {
      ...base.table,
      rows: data.alerts.slice(0, 4).map((item) => ({
        cells: [item.protocol, item.signal, item.action, item.priority],
        badge: item.state,
      })),
      footnote: data.conditions.proofPreference,
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Yield Delta",
            value: data.conditions.yieldDelta,
            tone: "teal",
          },
          {
            label: "Liquidity Guard",
            value: data.conditions.liquidityGuard,
            tone: "white",
          },
          {
            label: "Proof Preference",
            value: data.conditions.proofPreference,
            tone: "green",
          },
        ],
        footer: "Condition rules now come from a dedicated backend response.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Promote to Opportunity",
            value: data.quickActions.promoteToOpportunity,
            tone: "green",
          },
          {
            label: "Send to Agent",
            value: data.quickActions.sendToAgent,
            tone: "teal",
          },
          {
            label: "Archive Signal",
            value: data.quickActions.archiveSignal,
            tone: "white",
          },
        ],
        footer: "Quick actions stay in the same UI card while the source becomes backend-driven.",
      },
    ],
  };
}

export function mapSettingsApiToFeatureConfig(
  data: SettingsResponse,
): FeaturePageConfig {
  const base = getBaseConfig("settings");

  return {
    ...base,
    heroMetrics: [
      {
        label: "Risk Profile",
        value: data.hero.riskProfile,
        helper: "Current global execution posture",
      },
      {
        label: "Notification Rules",
        value: String(data.hero.notificationRules),
        helper: "Alert and proof update conditions",
        tone: "teal",
      },
      {
        label: "Explorer Default",
        value: data.hero.explorerDefault,
        helper: "Primary verification surface",
        tone: "green",
      },
      {
        label: "Agent Mode",
        value: data.hero.agentMode,
        helper: "Manual override still available",
      },
    ],
    highlight: {
      ...base.highlight,
      rows: [
        {
          label: "Max Slippage",
          value: data.preferences.maxSlippage,
          helper: base.highlight.rows[0].helper,
          tone: "green",
        },
        {
          label: "Proof Retention",
          value: data.preferences.proofRetention,
          helper: base.highlight.rows[1].helper,
          tone: "teal",
        },
        {
          label: "Auto-Execute",
          value: formatFeatureBoolean(data.preferences.autoExecute),
          helper: base.highlight.rows[2].helper,
          tone: "white",
        },
        {
          label: "Notification Mode",
          value: data.preferences.notificationMode,
          helper: base.highlight.rows[3].helper,
          tone: "white",
        },
      ],
      footer: "Settings now resolve from the GET /api/settings backend route.",
    },
    table: {
      ...base.table,
      rows: data.rules.slice(0, 4).map((item) => ({
        cells: [item.rule, item.scope, item.current, item.effect],
        badge: item.state,
      })),
      footnote: "PATCH /api/settings updates this backend shape without changing the layout.",
    },
    sideCards: [
      {
        ...base.sideCards[0],
        items: [
          {
            label: "Wallet Access",
            value: data.security.walletAccess,
            tone: "green",
          },
          {
            label: "Proof Visibility",
            value: data.security.proofVisibility,
            tone: "teal",
          },
          {
            label: "Manual Override",
            value: data.security.manualOverride,
            tone: "white",
          },
        ],
        footer: "Security card is now backed by structured settings data.",
      },
      {
        ...base.sideCards[1],
        items: [
          {
            label: "Sample Notifications",
            value: data.demoMode.sampleNotifications,
            tone: "teal",
          },
          {
            label: "Explorer Shortcut",
            value: data.demoMode.explorerShortcut,
            tone: "green",
          },
          {
            label: "Auto Prefill",
            value: data.demoMode.autoPrefill,
            tone: "white",
          },
        ],
        footer: "Demo mode stays polished while the backend state remains mutable.",
      },
    ],
  };
}
